export const ordersData = [
  {
    id: "AKN12508",
    customer: "Olivera Nules",
    order: "Nike Tshirt",
    delivery__date: "12.04.2021",
    price: "$24.90",
    status: "Resititute",
    payment__method: "Credit Card",
  },
  {
    id: "SRT32123",
    customer: "Alexandre Selinili",
    order: "Addidas Hat",
    delivery__date: "22.05.2021",
    price: "$19.90",
    status: "Complate",
    payment__method: "Bank Transfer",
  },
  {
    id: "TML30321",
    customer: "Selman Kalman",
    order: "Hummel Sneakers",
    delivery__date: "08.03.2021",
    price: "$89.90",
    status: "Complate",
    payment__method: "Credit Card",
  },
  {
    id: "KKA45012",
    customer: "David Dorenli",
    order: "Puma Shorts",
    delivery__date: "16.06.2021",
    price: "$19.90",
    status: "Resititute",
    payment__method: "Credit Card",
  },
  {
    id: "NNP23421",
    customer: "Marcus Genihales",
    order: "Nike Glove",
    delivery__date: "24.04.2021",
    price: "$39.90",
    status: "Continue",
    payment__method: "Bank Transfer",
  },
  {
    id: "TTS23089",
    customer: "Kemal Soloman",
    order: "Nike Hat",
    delivery__date: "14.04.2021",
    price: "$29.90",
    status: "Canceled",
    payment__method: "Bank Transfer",
  },
];
